import React, { useState } from 'react';
import { ArrowRight, Check, Code, Play, Sparkles, RefreshCw, Eye, MoveRight, Layers, Lock, Cpu } from 'lucide-react';

export const FederatedGatewayDemo: React.FC = () => {
  const [activeStep, setActiveStep] = useState<1 | 2 | 3>(1);
  const [selectedEndpoint, setSelectedEndpoint] = useState<'hubspot' | 'brevo' | 'stripe'>('hubspot');
  const [boundTokens, setBoundTokens] = useState<Record<string, string>>({
    'title': 'gateway.hubspot.deal_name',
    'value': 'gateway.hubspot.deal_value',
    'owner': 'gateway.hubspot.owner_email',
  });
  const [isBinding, setIsBinding] = useState(false);

  const rawResponses = {
    hubspot: {
      url: 'https://api.hubspot.com/crm/v3/objects/deals/10928472',
      json: `{
  "id": "10928472",
  "properties": {
    "dealname": "Enterprise Multi-Region License",
    "amount": "142500.00",
    "dealstage": "contract_signed",
    "closedate": "2026-09-30T18:00:00Z",
    "hubspot_owner_id": "owner_7719",
    "owner_email": "sarah.connor@acme-corp.com"
  },
  "createdAt": "2026-09-12T14:22:10.822Z",
  "archived": false
}`,
      zod: `// Auto-generated by @whoobe-cms/gateway
import { z } from 'zod';

export const HubSpotDealSchema = z.object({
  id: z.string(),
  properties: z.object({
    dealname: z.string().min(1),
    amount: z.coerce.number().positive(),
    dealstage: z.enum(['discovery', 'proposal', 'contract_signed']),
    closedate: z.string().datetime(),
    owner_email: z.string().email()
  }),
  createdAt: z.string().datetime(),
  archived: z.boolean()
});

export type HubSpotDeal = z.infer<typeof HubSpotDealSchema>;`,
      tokens: [
        { key: 'gateway.hubspot.deal_name', label: 'dealname', sample: 'Enterprise Multi-Region License', type: 'string' },
        { key: 'gateway.hubspot.deal_value', label: 'amount', sample: '$142,500.00', type: 'currency' },
        { key: 'gateway.hubspot.deal_stage', label: 'dealstage', sample: 'Contract Signed', type: 'enum' },
        { key: 'gateway.hubspot.owner_email', label: 'owner_email', sample: 'sarah.connor@acme-corp.com', type: 'email' },
      ],
      previewCard: {
        title: 'Enterprise Multi-Region License',
        badge: 'Contract Signed',
        amount: '$142,500.00',
        contact: 'sarah.connor@acme-corp.com',
      }
    },
    brevo: {
      url: 'https://api.brevo.com/v3/contacts/segment/vip_enterprise',
      json: `{
  "email": "cto@techglobal.de",
  "attributes": {
    "FIRSTNAME": "Maximilian",
    "LASTNAME": "Vogel",
    "TIER": "Enterprise VIP",
    "CREDITS_REMAINING": 45000,
    "CAMPAIGN_CONSENT": true
  },
  "listIds": [42, 88]
}`,
      zod: `// Auto-generated by @whoobe-cms/gateway
import { z } from 'zod';

export const BrevoContactSchema = z.object({
  email: z.string().email(),
  attributes: z.object({
    FIRSTNAME: z.string(),
    LASTNAME: z.string(),
    TIER: z.string(),
    CREDITS_REMAINING: z.number().int().nonnegative(),
    CAMPAIGN_CONSENT: z.boolean()
  }),
  listIds: z.array(z.number())
});

export type BrevoContact = z.infer<typeof BrevoContactSchema>;`,
      tokens: [
        { key: 'gateway.brevo.email', label: 'email', sample: 'cto@techglobal.de', type: 'email' },
        { key: 'gateway.brevo.name', label: 'FIRSTNAME + LASTNAME', sample: 'Maximilian Vogel', type: 'string' },
        { key: 'gateway.brevo.tier', label: 'TIER', sample: 'Enterprise VIP', type: 'string' },
        { key: 'gateway.brevo.credits', label: 'CREDITS_REMAINING', sample: '45,000 Credits', type: 'number' },
      ],
      previewCard: {
        title: 'Maximilian Vogel',
        badge: 'Enterprise VIP',
        amount: '45,000 Credits',
        contact: 'cto@techglobal.de',
      }
    },
    stripe: {
      url: 'https://api.stripe.com/v1/subscriptions/sub_1Og782x98',
      json: `{
  "id": "sub_1Og782x98",
  "status": "active",
  "customer": "cus_991823",
  "plan": {
    "nickname": "Whoobe Enterprise Dedicated",
    "amount": 240000,
    "currency": "usd",
    "interval": "year"
  },
  "current_period_end": 1790683200
}`,
      zod: `// Auto-generated by @whoobe-cms/gateway
import { z } from 'zod';

export const StripeSubscriptionSchema = z.object({
  id: z.string().startsWith('sub_'),
  status: z.enum(['active', 'past_due', 'canceled']),
  customer: z.string(),
  plan: z.object({
    nickname: z.string(),
    amount: z.number().int(),
    currency: z.string().length(3),
    interval: z.enum(['month', 'year'])
  }),
  current_period_end: z.number().int()
});`,
      tokens: [
        { key: 'gateway.stripe.plan_name', label: 'plan.nickname', sample: 'Whoobe Enterprise Dedicated', type: 'string' },
        { key: 'gateway.stripe.amount', label: 'plan.amount', sample: '$2,400.00 / yr', type: 'currency' },
        { key: 'gateway.stripe.status', label: 'status', sample: 'Active', type: 'status' },
      ],
      previewCard: {
        title: 'Whoobe Enterprise Dedicated',
        badge: 'Active Subscription',
        amount: '$2,400.00 / yr',
        contact: 'Customer ID: cus_991823',
      }
    }
  };

  const current = rawResponses[selectedEndpoint];

  const handleSimulateTokenDrop = (tokenKey: string, field: string) => {
    setIsBinding(true);
    setTimeout(() => {
      setBoundTokens(prev => ({ ...prev, [field]: tokenKey }));
      setIsBinding(false);
    }, 300);
  };

  return (
    <div className="w-full rounded-2xl bg-[#12151B] border border-white/10 overflow-hidden shadow-2xl">
      {/* Header Bar */}
      <div className="bg-[#1A1D24] px-6 py-4 border-b border-white/10 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-[#7C3AED]/20 text-[#A78BFA] border border-[#7C3AED]/30">
            <Cpu className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-base font-semibold text-white font-heading">
              Federated API Gateway & Auto-Discovery Engine
            </h3>
            <p className="text-xs text-slate-400">
              Zero custom bridge code · Real-time Zod schema synthesis · Direct visual token injection
            </p>
          </div>
        </div>

        {/* Endpoint Selector Tabs */}
        <div className="flex items-center bg-[#0F1115] p-1 rounded-lg border border-white/10 text-xs font-mono">
          <button
            onClick={() => setSelectedEndpoint('hubspot')}
            className={`px-3 py-1.5 rounded-md transition-colors ${
              selectedEndpoint === 'hubspot' ? 'bg-[#7C3AED] text-white font-semibold' : 'text-slate-400 hover:text-white'
            }`}
          >
            HubSpot CRM
          </button>
          <button
            onClick={() => setSelectedEndpoint('brevo')}
            className={`px-3 py-1.5 rounded-md transition-colors ${
              selectedEndpoint === 'brevo' ? 'bg-[#7C3AED] text-white font-semibold' : 'text-slate-400 hover:text-white'
            }`}
          >
            Brevo Marketing
          </button>
          <button
            onClick={() => setSelectedEndpoint('stripe')}
            className={`px-3 py-1.5 rounded-md transition-colors ${
              selectedEndpoint === 'stripe' ? 'bg-[#7C3AED] text-white font-semibold' : 'text-slate-400 hover:text-white'
            }`}
          >
            Stripe OpenAPI
          </button>
        </div>
      </div>

      {/* 3-Step Wizard Navigation */}
      <div className="grid grid-cols-1 md:grid-cols-3 border-b border-white/10 bg-[#161A22]">
        <button
          onClick={() => setActiveStep(1)}
          className={`px-6 py-3.5 flex items-center gap-3 text-left transition-all border-b-2 md:border-b-0 md:border-r border-white/5 ${
            activeStep === 1 ? 'border-[#7C3AED] bg-white/[0.03]' : 'border-transparent opacity-70 hover:opacity-100'
          }`}
        >
          <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-mono font-bold ${
            activeStep === 1 ? 'bg-[#7C3AED] text-white shadow-md' : 'bg-white/10 text-slate-300'
          }`}>
            1
          </div>
          <div>
            <div className="text-xs font-semibold text-white font-heading">Raw Inbound REST</div>
            <div className="text-[11px] text-slate-400">Inspect external JSON payload</div>
          </div>
        </button>

        <button
          onClick={() => setActiveStep(2)}
          className={`px-6 py-3.5 flex items-center gap-3 text-left transition-all border-b-2 md:border-b-0 md:border-r border-white/5 ${
            activeStep === 2 ? 'border-[#0891B2] bg-white/[0.03]' : 'border-transparent opacity-70 hover:opacity-100'
          }`}
        >
          <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-mono font-bold ${
            activeStep === 2 ? 'bg-[#0891B2] text-white shadow-md' : 'bg-white/10 text-slate-300'
          }`}>
            2
          </div>
          <div>
            <div className="text-xs font-semibold text-white font-heading">Zod Auto-Discovery</div>
            <div className="text-[11px] text-slate-400">Strict runtime TypeScript guards</div>
          </div>
        </button>

        <button
          onClick={() => setActiveStep(3)}
          className={`px-6 py-3.5 flex items-center gap-3 text-left transition-all ${
            activeStep === 3 ? 'border-[#7C3AED] bg-white/[0.03]' : 'border-transparent opacity-70 hover:opacity-100'
          }`}
        >
          <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-mono font-bold ${
            activeStep === 3 ? 'bg-[#7C3AED] text-white shadow-md' : 'bg-white/10 text-slate-300'
          }`}>
            3
          </div>
          <div>
            <div className="text-xs font-semibold text-white font-heading">Visual Token Binding</div>
            <div className="text-[11px] text-slate-400">Drop tokens into UI canvas blocks</div>
          </div>
        </button>
      </div>

      {/* Main Interactive Stage */}
      <div className="p-6">
        {activeStep === 1 && (
          <div className="space-y-4 animate-in fade-in duration-200">
            <div className="flex items-center justify-between bg-[#0B0D11] px-4 py-2.5 rounded-lg border border-white/10">
              <div className="flex items-center gap-2 overflow-x-auto text-xs font-mono">
                <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-400 font-bold border border-emerald-500/30">
                  GET
                </span>
                <span className="text-slate-300">{current.url}</span>
              </div>
              <div className="flex items-center gap-1.5 text-xs text-slate-400">
                <Lock className="w-3.5 h-3.5 text-[#0891B2]" />
                <span className="font-mono">AES-256 Proxy</span>
              </div>
            </div>

            <div className="relative">
              <pre className="p-4 rounded-xl bg-[#090B0E] border border-white/5 text-xs font-mono text-cyan-300/90 overflow-x-auto max-h-[300px] leading-relaxed">
                {current.json}
              </pre>
              <div className="absolute top-3 right-3 text-[11px] text-slate-500 font-mono">
                HTTP 200 OK (38ms)
              </div>
            </div>

            <div className="flex justify-end pt-2">
              <button
                onClick={() => setActiveStep(2)}
                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#0891B2] hover:bg-[#0E7490] text-white text-xs font-semibold transition-colors cursor-pointer"
              >
                <span>Run Schema Auto-Discovery</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        )}

        {activeStep === 2 && (
          <div className="space-y-4 animate-in fade-in duration-200">
            <div className="flex items-center justify-between bg-[#0B0D11] px-4 py-2.5 rounded-lg border border-white/10 text-xs">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-cyan-400 animate-ping" />
                <span className="text-white font-mono">Auto-generated TypeScript Guard</span>
              </div>
              <span className="text-xs font-mono text-slate-400">Zod 3.23 · Zero Runtime Overhead</span>
            </div>

            <pre className="p-4 rounded-xl bg-[#090B0E] border border-cyan-900/30 text-xs font-mono text-purple-300/90 overflow-x-auto max-h-[300px] leading-relaxed">
              {current.zod}
            </pre>

            <div className="flex justify-between items-center pt-2">
              <button
                onClick={() => setActiveStep(1)}
                className="text-xs text-slate-400 hover:text-white transition-colors"
              >
                ← Back to Raw JSON
              </button>
              <button
                onClick={() => setActiveStep(3)}
                className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#7C3AED] hover:bg-[#6D28D9] text-white text-xs font-semibold transition-colors cursor-pointer"
              >
                <span>Inject Tokens into Visual Canvas</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        )}

        {activeStep === 3 && (
          <div className="space-y-6 animate-in fade-in duration-200">
            <div className="text-xs text-slate-400">
              Discovered fields become live data tokens. Click a token below to bind it to the target component slot on the right:
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
              
              {/* Token Palette (Left 5 cols) */}
              <div className="lg:col-span-5 space-y-3 bg-[#0B0D11] p-4 rounded-xl border border-white/5">
                <div className="text-xs font-semibold text-slate-300 uppercase tracking-wider font-mono flex items-center justify-between">
                  <span>Discovered Tokens</span>
                  <span className="text-[10px] text-cyan-400">Ready for Binding</span>
                </div>

                <div className="space-y-2">
                  {current.tokens.map((token) => (
                    <div
                      key={token.key}
                      onClick={() => handleSimulateTokenDrop(token.key, 'value')}
                      className="p-2.5 rounded-lg bg-[#161A22] border border-white/10 hover:border-[#7C3AED] hover:bg-[#1E1B4B]/30 cursor-pointer transition-all flex items-center justify-between group"
                    >
                      <div className="space-y-0.5">
                        <div className="flex items-center gap-1.5">
                          <span className="text-xs font-mono text-cyan-400 group-hover:text-cyan-300">
                            {token.key}
                          </span>
                        </div>
                        <div className="text-[11px] text-slate-400">
                          Sample: <span className="text-white font-medium">{token.sample}</span>
                        </div>
                      </div>
                      <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded bg-white/5 text-slate-400">
                        {token.type}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Live Canvas Component Block (Right 7 cols) */}
              <div className="lg:col-span-7 space-y-3">
                <div className="text-xs font-semibold text-slate-300 uppercase tracking-wider font-mono flex items-center justify-between">
                  <span>Visual Canvas Component Block</span>
                  <span className="text-[10px] text-emerald-400 flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                    Live Hydration (SSR/ISR)
                  </span>
                </div>

                {/* Simulated Visual Builder Element */}
                <div className="p-6 rounded-xl bg-gradient-to-br from-[#1A1D24] to-[#12151B] border-2 border-dashed border-[#7C3AED]/50 shadow-xl space-y-4">
                  <div className="flex items-center justify-between border-b border-white/10 pb-3">
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 rounded-full bg-[#7C3AED]" />
                      <span className="text-xs font-mono text-slate-400">Block: DealSummaryCard.tsx</span>
                    </div>
                    <span className="text-xs font-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                      {current.previewCard.badge}
                    </span>
                  </div>

                  <div className="space-y-3">
                    <div>
                      <div className="text-[10px] uppercase font-mono text-slate-400 mb-1">
                        Token Binding: {'{{ '}{boundTokens['title'] || 'gateway.hubspot.deal_name'}{' }}'}
                      </div>
                      <h4 className="text-xl font-bold text-white font-heading">
                        {current.previewCard.title}
                      </h4>
                    </div>

                    <div className="p-3 rounded-lg bg-[#0F1115] border border-white/5 flex items-center justify-between">
                      <div>
                        <div className="text-[10px] uppercase font-mono text-slate-400">
                          Bound Value: {'{{ '}{boundTokens['value'] || 'gateway.hubspot.deal_value'}{' }}'}
                        </div>
                        <div className="text-2xl font-black text-cyan-400 font-mono">
                          {current.previewCard.amount}
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="text-[10px] uppercase font-mono text-slate-400">Assignee / Owner</div>
                        <div className="text-xs text-slate-300 font-mono">
                          {current.previewCard.contact}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="pt-2 flex items-center justify-between text-[11px] text-slate-400">
                    <span>Target: Next.js 15 & Capacitor Native APK</span>
                    <span className="text-emerald-400 font-mono">✓ Validated against Zod Schema</span>
                  </div>
                </div>

                <div className="flex items-center justify-between pt-2">
                  <button
                    onClick={() => setActiveStep(2)}
                    className="text-xs text-slate-400 hover:text-white transition-colors"
                  >
                    ← Back to Zod Guards
                  </button>
                  <button
                    onClick={() => {
                      setBoundTokens({
                        'title': current.tokens[0].key,
                        'value': current.tokens[1].key,
                        'owner': current.tokens[2]?.key || '',
                      });
                    }}
                    className="flex items-center gap-1.5 text-xs text-[#A78BFA] hover:text-white transition-colors"
                  >
                    <RefreshCw className="w-3 h-3" />
                    <span>Reset Token Mappings</span>
                  </button>
                </div>
              </div>

            </div>
          </div>
        )}
      </div>
    </div>
  );
};
